### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by morenoh149** [sunnysid3up/python-linter#8]
I get an error
```
No event triggers defined in 'on'
```
![Screen Shot 2023-05-17 at 4 35 31 PM](https://github.com/sunnysid3up/python-linter/assets/587438/fa98b515-12d7-40c0-a168-1908beff71c6)
![Screen Shot 2023-05-17 at 4 35 26 PM](https://github.com/sunnysid3up/python-linter/assets/587438/9795b443-ddea-4623-b0f8-6dd2f03b582f)

**Comment by till** [comment]
You need a complete workflow.

```yaml
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
```

Maybe take a look at the official docs:
https://docs.github.com/en/actions/using-workflows
